---
title: "Time Series Code Sketches"
output: html_notebook
---
```{r}
library(magrittr)
library(ggplot2)
library(dplyr)
library(tidyr)
```


Random walk, testing for autocorrelation

```{r}
size = 1000
e.series <- rnorm(size, mean = 0, sd = 1)
#e.series <- runif(size, min = -3, max = 3)

# Cauchy Distribution might be interesting to experiment with, as it has no higher moments and can generate some huge jumps in a random walk 
# Simulates a time series subject to massive disturbances
#e.series <- rcauchy(size, location = 0, scale = 1)


Y <- 0 #initial condition

for (i in 1:length(e.series)){
  Y <- c(Y, Y[i-1] + e.series[i])
}

plot(Y, type = "o", ylab = "Random Walk")

Y <- 0 #initial condition

for (i in 1:length(e.series)){
  Y <- c(Y, Y[i-1] + e.series[i])
}

plot(Y, type = "l", ylab = "Random Walk")
```

A conclusion from the book: for a random walk, values of Y are more and more strongly correlated at t increases (time goes by), but values of Y are less and less correlated the farther apart they are (see 1,25 = 0.2). How can this be shown graphically?


values of Y are less and less correlated the farther apart they are
```{r}
corr.distance = NULL
window = 100

for (i in seq(1, window, 20)) {
  corr.distance.obs = NULL
  
  for (j in 1:window) {
    
    corr.iter <- cor(Y[i:(window + i - 1)], Y[j:(window + j - 1)])
    corr.distance.obs <- c(corr.distance.obs, corr.iter)
  }
  
  corr.distance <- rbind(corr.distance, corr.distance.obs)
    
}

#head(corr.distance)
```

```{r}
time.scale <- rep(1:100, 100)
corr.distance <- matrix(corr.distance, nrow = 5, ncol = 100) %>% 
  t() %>%
  as.data.frame() %>%
  gather() %>%
  cbind(time.scale)

ggplot(corr.distance, aes(x = time.scale, y = value, color = key)) + geom_line()
```

